# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab3/Lab3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3 || ORIG_REF_NAME==Lab3}]

# IP: bd/Lab3/ip/Lab3_processing_system7_0_0/Lab3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_processing_system7_0_0 || ORIG_REF_NAME==Lab3_processing_system7_0_0}]

# IP: bd/Lab3/ip/Lab3_MYMULTIPLIER_0_0/Lab3_MYMULTIPLIER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_MYMULTIPLIER_0_0 || ORIG_REF_NAME==Lab3_MYMULTIPLIER_0_0}]

# IP: bd/Lab3/ip/Lab3_processing_system7_0_axi_periph_0/Lab3_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==Lab3_processing_system7_0_axi_periph_0}]

# IP: bd/Lab3/ip/Lab3_rst_processing_system7_0_100M_0/Lab3_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Lab3_rst_processing_system7_0_100M_0}]

# IP: bd/Lab3/ip/Lab3_auto_pc_0/Lab3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_auto_pc_0 || ORIG_REF_NAME==Lab3_auto_pc_0}]

# XDC: bd/Lab3/ip/Lab3_processing_system7_0_0/Lab3_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Lab3_processing_system7_0_0 || ORIG_REF_NAME==Lab3_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Lab3/ip/Lab3_rst_processing_system7_0_100M_0/Lab3_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Lab3_rst_processing_system7_0_100M_0}]

# XDC: bd/Lab3/ip/Lab3_rst_processing_system7_0_100M_0/Lab3_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Lab3_rst_processing_system7_0_100M_0}]

# XDC: bd/Lab3/ip/Lab3_rst_processing_system7_0_100M_0/Lab3_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/Lab3/ip/Lab3_auto_pc_0/Lab3_auto_pc_0_ooc.xdc

# XDC: bd/Lab3/Lab3_ooc.xdc
