# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/INTRA/guyild/workspace/lab3/vivado/lab3.cache/wt [current_project]
set_property parent.project_path /home/INTRA/guyild/workspace/lab3/vivado/lab3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/INTRA/guyild/workspace/lab3/ip_repo/MYMULTIPLIER_1.0 [current_project]
add_files /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/Lab3.bd
set_property used_in_implementation false [get_files -all /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/ip/Lab3_processing_system7_0_0/Lab3_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/ip/Lab3_rst_processing_system7_0_100M_0/Lab3_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/ip/Lab3_rst_processing_system7_0_100M_0/Lab3_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/ip/Lab3_rst_processing_system7_0_100M_0/Lab3_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/ip/Lab3_auto_pc_0/Lab3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/Lab3_ooc.xdc]
set_property is_locked true [get_files /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/Lab3.bd]

read_vhdl -library xil_defaultlib /home/INTRA/guyild/workspace/lab3/vivado/lab3.srcs/sources_1/bd/Lab3/hdl/Lab3_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top Lab3_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef Lab3_wrapper.dcp
catch { report_utilization -file Lab3_wrapper_utilization_synth.rpt -pb Lab3_wrapper_utilization_synth.pb }
